#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: recipes/04_postprocess_ctms.sh <segments_list> <recipe>"
    echo "e.g.: $0 segments.list /path/to/recipe_file"
    echo
    echo "Postprocess CTMs in <segments_list> (generated in the previous step)."
    echo "In postprocessing, the CTM is matched to the original transcript to determine"
    echo "speaker and language. Any sample with multiple speakers or Swedish is dropped"
    echo "from the segments generated by the Kaldi segmentation script."
    echo
    exit 1
fi

SEGMENTS_LIST=$1
RECIPE=$2

poetry run fi-parliament-tools postprocess $SEGMENTS_LIST $RECIPE
